[tool.poetry]
name = "ingrid-flogny"
version = "0.1.0"
description = ""
authors = ["iflogny <iflogny@synergy.fr>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
